services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Obsidiane\Notifuse\Service\ApiClient:
    arguments:
      $apiBaseUrl: '%notifuse.api_base_url%'
      $workspaceId: '%notifuse.workspace_id%'
      $workspaceApiKey: '%notifuse.workspace_api_key%'
      $options: '%notifuse.http_client_options%'

